version: "3.8"

services:
  # PostgreSQL Database
  database:
    image: postgres:16-alpine
    container_name: raastabuzz_db
    environment:
      POSTGRES_DB: raastabuzz
      POSTGRES_USER: raastauser
      POSTGRES_PASSWORD: raastapass
    volumes:
      - raastabuzz_postgres_data:/var/lib/postgresql/data
      # Optional: Add init scripts if needed
      # - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - raastabuzz-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raastauser -d raastabuzz"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Spring Boot Backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: raastabuzz_backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/raastabuzz
      SPRING_DATASOURCE_USERNAME: raastauser
      SPRING_DATASOURCE_PASSWORD: raastapass
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_DATASOURCE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - raastabuzz-network
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: raastabuzz_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - raastabuzz-network

volumes:
  raastabuzz_postgres_data:

networks:
  raastabuzz-network:
    driver: bridge
