name: Deploy to Azure VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Get the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # - name: Run tests
      #   run: |
      #     cd Backend
      #     # mvn clean test
      #   env:
      #     SPRING_PROFILES_ACTIVE: test
      #     SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      #     SPRING_DATASOURCE_USERNAME: sa
      #     SPRING_DATASOURCE_PASSWORD: password
      #     SPRING_DATASOURCE_DRIVER: org.h2.Driver
      #     SPRING_DATASOURCE_DIALECT: org.hibernate.dialect.H2Dialect
      #     SPRING_JPA_HIBERNATE_DDL_AUTO: update
      #     SPRING_JPA_SHOW_SQL: false
      #     FIREBASE_KEY: "${{ secrets.FIREBASE_KEY }}$"
      #     FIREBASE_STORAGE_BUCKET: test-bucket
      #     JWT_SECRET: ${{ secrets.JWT_SECRET }}

      # 3. Build backend JAR
      # - name: Build backend JAR
      #   run: |
      #     cd Backend
      #     chmod +x mvnw
      #     ./mvnw clean package -DskipTests
      #     ls -la target/

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "20"
      #     cache: "npm"
      #     cache-dependency-path: Frontend/package-lock.json

      # - name: Install frontend dependencies
      #   run: |
      #     cd Frontend
      #     npm ci
      #     # npm test

      # 4. Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # 5. Build and push backend
      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/raastabuzz-backend:latest ./Backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/raastabuzz-backend:latest

      # 6. Build and push frontend
      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/raastabuzz-frontend:latest ./Frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/raastabuzz-frontend:latest
